In [1]:
# import library pandas
import pandas as pd 

# Import library numpy
import numpy as np

# Import library matplotlib dan seaborn untuk visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# me-non aktifkan peringatan pada python
import warnings 
warnings.filterwarnings('ignore')

ModuleNotFoundError: No module named 'pandas'

In [ ]:
#Panggil file dan simpan dalam dataframe
dataset = pd.read_csv("dit.csv", usecols = ['kota', 'kec', 'trw', 'trt', 'tkk', 'tj'])

In [ ]:
# tampilkan 5 baris data 
dataset.head(5)

kota  kec  trw  trt  tkk   tj
0     1    1    4    4   35  140
1     1    2    4    4    0    0
2     1    2    4    4    0    0
3     1    3    7    7  155  625
4     1    4    2    2   52  195

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kota    150 non-null    int64
 1   kec     150 non-null    int64
 2   trw     150 non-null    int64
 3   trt     150 non-null    int64
 4   tkk     150 non-null    int64
 5   tj      150 non-null    int64
dtypes: int64(6)
memory usage: 7.2 KB


In [ ]:
dataset.corr()

kota       kec       trw       trt       tkk        tj
kota  1.000000  0.951958 -0.075578  0.152242  0.157233  0.126701
kec   0.951958  1.000000 -0.092211  0.181266  0.180618  0.139086
trw  -0.075578 -0.092211  1.000000  0.595282  0.385286  0.382779
trt   0.152242  0.181266  0.595282  1.000000  0.549245  0.497684
tkk   0.157233  0.180618  0.385286  0.549245  1.000000  0.979855
tj    0.126701  0.139086  0.382779  0.497684  0.979855  1.000000

In [ ]:
X=dataset.iloc[:,0:5].values
y=dataset.iloc[:,5].values

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
#Metrics
from sklearn.metrics import make_scorer, accuracy_score,precision_score
from sklearn.metrics import classification_report

# Import Library Confussion Matrix
from sklearn.metrics import confusion_matrix

from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

#Model Select
from sklearn.model_selection import KFold,train_test_split,cross_val_score

# Import Library Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split

# from sklearn import linear_model
from sklearn import linear_model

In [ ]:
#Train and Test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1,random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver= 'lbfgs',max_iter=400)
logreg.fit(X_train, y_train)
Y_pred = logreg.predict(X_test)
accuracy_lr=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_log = round(logreg.score(X_train, y_train) * 100, 2)


cm = confusion_matrix(y_test,Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision = precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Logistic Regression\n',cm)
print('accuracy_Logistic Regression : %.3f' %accuracy)
print('precision_Logistic Regression : %.3f' %precision)
print('recall_Logistic Regression: %.3f' %recall)
print('f1-score_Logistic Regression : %.3f' %f1)

Confusion matrix for Logistic Regression
 [[6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
accuracy_Logistic Regression : 0.400
precision_Logistic Regression : 0.400
recall_Logistic Regression: 0.400
f1-score_Logistic Regression : 0.400


In [ ]:
predictions = logreg.predict(X_test)
predictions[:10]

array([18, 47,  0, 27, 89, 27,  0, 47, 81, 70], dtype=int64)

In [ ]:
import joblib
joblib.dump(logreg, 'logreg_model.pkl')

['logreg_model.pkl']